// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhvfyvkckqhalqhosisp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhodmZ5dmtja3FoYWxxaG9zaXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDg2NTAsImV4cCI6MjA2NjYyNDY1MH0.fpvHvJrdG7_vNvRPWrTglfCM1QzheTh96eRI7t9DurM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);